apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: ticketing
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-301116
  artifacts:
    - image: gcr.io/ticketing-dev-301116/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
