apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: ulab.xyz
      http:
        paths:
          - path: /api/users/.*
            backend:
              serviceName: auth-cip-srv
              servicePort: 3000
